import React from "react";
import jsStyle from "./css/JavasCript_Lesson.module.css";
import {faDotCircle} from "@fortawesome/free-solid-svg-icons/faDotCircle";
import "./css/CodingExamples.css";
import "./css/bbc.css"

import {Prism as SyntaxHighlighter} from 'react-syntax-highlighter';
import docco from "react-syntax-highlighter/dist/esm/styles/hljs/docco";

const one = "Robby ";

function JavaScriptLessonObject() {
    return (
        [
            {
                title: [<div><p className={jsStyle.title}>Overview</p></div>],
            },

            {
                titleName: "Indorction",
                heading: 'What is JavaScript ?',
                iconName: faDotCircle,
                description: [
                    `
                    JavaScript is a dynamic computer programming language.
                    It is lightweight and most commonly
                    used as a part of web pages, whose implementations
                    allow client-side script to interact with the user and make dynamic pages.
                    It is an interpreted programming language with object-oriented capabilities.

                    <br class="br_description" />

                    JavaScript was first known as <b class="hal">LiveScript</b>, but Netscape changed its name to JavaScript,
                    possibly because of the excitement being generated by Java.
                    JavaScript made its first appearance in Netscape 2.0 in 1995 with the name <b class="hal">LiveScript</b>.
                    The general-purpose core of the language has been embedded in Netscape, Internet Explorer, and other web browsers.

                    <br class="br_description" />

                    <h2 class="title_description">Client-Side JavaScript</h2>

                    Client-side JavaScript is the most common form of the language. The script should be included in or
                    referenced by an HTML document for the code to be interpreted by the browser.
                    It means that a web page need not be a static HTML, but can include programs that interact with the user,
                    control the browser, and dynamically create HTML content.

                    <br class="br_description" />

                    The JavaScript client-side mechanism provides many advantages over traditional CGI server-side scripts.
                    For example, you might use JavaScript to check if the user has entered a valid e-mail address in a form field.

                    <br class="br_description" />

                    The JavaScript code is executed when the user submits the form,
                    and only if all the entries are valid, they would be submitted to the Web Server.
                    JavaScript can be used to trap user-initiated events such as button clicks, link navigation, and other actions that the user initiates explicitly or implicitly.

                    <h2 class="title_description">JavaScript Development Tools</h2>

                    One of major strengths of JavaScript is that it does not require expensive development tools.
                    You can start with a simple text editor such as Notepad.
                    Since it is an interpreted language inside the context of a web browser, you don't even need to buy a compiler.

                    <br class="br_description" />

                    To make our life simpler, various vendors have come up with very nice JavaScript editing tools. Some of them are listed here −
                    
                    <ul class="js_ul_list">
                        <li> <b class="hal">Microsoft FrontPage − </b> Microsoft has developed a popular HTML editor called FrontPage.
                        FrontPage also provides web developers with a number of
                        JavaScript tools to assist in the creation of interactive websites.</li>
                        
                        <li> <b class="hal">Macromedia Dreamweaver MX − </b> Macromedia Dreamweaver MX is a very popular HTML
                        and JavaScript editor in the professional web development crowd.
                        It provides several handy prebuilt JavaScript components,
                        integrates well with databases, and conforms to new standards such as XHTML and XML.</li>

                        <li> <b class="hal">Macromedia HomeSite 5 − </b> HomeSite 5 is a well-liked HTML
                        and JavaScript editor from Macromedia that can
                        be used to manage personal websites effectively.</li>
                    </ul>
                    
                    <h2 class="title_description">Where is JavaScript Today ?</h2>
                    
                    The ECMAScript Edition 5 standard will be the first update to be released in over four years.
                    JavaScript 2.0 conforms to Edition 5 of the ECMAScript standard, and the difference between the two is extremely minor.
                    The specification for JavaScript 2.0 can be found on the following site:
                    <a class="link_description" target="_blank" href="http://www.ecma-international.org/ecma-262/6.0/">http://www.ecmascript.org/</a>
                    
                    <br class="br_description" />
                    
                    Today, Netscape's JavaScript and Microsoft's JScript conform to the ECMAScript standard,
                    although both the languages still support the features that are not a part of the standard.
                    `
                ],
            },

            {
                titleName: "Creating Your First JavaScript",
                heading: 'Ready. Set. JavaScript!',
                iconName: faDotCircle,
                description: [
                    `

                    <h2 class="title_description">Let’s start</h2>
                    With the basics and add some JavaScript to a web page. On the web, JavaScript code lives inside the HTML
                    document, and needs to be enclosed by

<pre>
<code id=code-html class="code xml" data-clipboard-target="#code-html">
&lt;!-- html markup --&gt;
&lt;nav&gt;
    &lt;ul&gt;
        &lt;li&gt;&lt;a href="#">Home&lt;/a&gt;&lt;/li&gt;
        &lt;li&gt;&lt;a href="">About me&lt;/a&gt;&lt;/li&gt;
        &lt;li&gt;&lt;a href="">Projects&lt;/a&gt;&lt;/li&gt;
        &lt;li&gt;&lt;a href="">Contact&lt;/a&gt;&lt;/li&gt;
    &lt;/ul&gt;
&lt;/nav&gt;
        </code>
        <label>1.1: Bizzsle fo shizzle my nizzle urna, pimpin' yo mamma.</label>
    </pre>
<p>
\t\t2. Phasellizzle dang volutpizzle tellizzle. Ut the bizzle adipiscing crunk. Donizzle dang est. Away pot massa, doggy nizzle, accumsan sizzle, fermentizzle quizzle, pede. Ducis ass libero. Pot shiznit ornare ante. Dizzle for sure. Get down get down own
\t\tyo' pede gizzle nibh commodo commodo. Sure crunk dolizzle sizzle check it out, bizzle my shizz. Uhuh ... yih! bow wow wow shizzle my nizzle crocodizzle. I saw beyonces tizzles and my pizzle went crizzle tellivizzle sizzle, phat izzle, mattizzle a, eleifend
\t\trizzle, tellivizzle.
</p>


<pre>
                  `
                ],
            },

            {
                titleName: "JS Output",
                iconName: faDotCircle,
                description: [
                    <span className={jsStyle.yourClass}>{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.`
                ],
            },

            {
                titleName: "JS Statements",
                iconName: faDotCircle,
                description: [
                    <span className={jsStyle.yourClass}>{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.1`
                ],
            },

            {
                titleName: "JS Syntax",
                iconName: faDotCircle,
                description: [
                    <span className={jsStyle.yourClass}>{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.`
                ],
            },

            {
                titleName: "JS Comments",
                iconName: faDotCircle,
                description: [
                    <span className={jsStyle.yourClass}>{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.1`
                ],
            },

            {
                titleName: "JS Variables",
                iconName: faDotCircle,
                description: [
                    <span className="yourClass">{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.`
                ],
            },

            {
                title: [<span className={jsStyle.title}>Basic Concepts</span>],
            },

            {
                titleName: "JS Forms",
                iconName: faDotCircle,
                description: [
                    <span className="yourClass">{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.`
                ],
            },

            {
                titleName: "Forms API",
                iconName: faDotCircle,
                description: [
                    <span className="yourClass">{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.1`
                ],
            },

            {
                titleName: "JS Forms",
                iconName: faDotCircle,
                description: [
                    <span className="yourClass">{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.`
                ],
            },

            {
                titleName: "Forms API",
                iconName: faDotCircle,
                description: [
                    <span className="yourClass">{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.1`
                ],
            },

            {
                titleName: "JS Forms",
                iconName: faDotCircle,
                description: [
                    <span className="yourClass">{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.`
                ],
            },

            {
                titleName: "Forms API",
                iconName: faDotCircle,
                description: [
                    <span className="yourClass">{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.1`
                ],
            },

            {
                title: [<span className={jsStyle.title}>Conditionals and Loops</span>],
            },

            {
                titleName: "Object Definitions",
                iconName: faDotCircle,
                description: [
                    <span className="yourClass">{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.1`
                ],
            },

            {
                titleName: "Object Properties",
                iconName: faDotCircle,
                description: [
                    <span className="yourClass">{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.`
                ],
            },

            {
                titleName: "Object Methods",
                iconName: faDotCircle,
                description: [
                    <span className="yourClass">{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.1`
                ],
            },

            {
                titleName: "Object Display",
                iconName: faDotCircle,
                description: [
                    <span className="yourClass">{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.`
                ],
            },

            {
                titleName: "Object Accessors",
                iconName: faDotCircle,
                description: [
                    <span className="yourClass">{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.1`
                ],
            },

            {
                titleName: "Object Constructors",
                iconName: faDotCircle,
                description: [
                    <span className="yourClass">{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.`
                ],
            },

            {
                title: [<span className={jsStyle.title}>Functions</span>],
            },

            {
                titleName: "JS Events",
                iconName: faDotCircle,
                description: [
                    <span className="yourClass">{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.1`
                ],
            },

            {
                titleName: "JS Strings",
                iconName: faDotCircle,
                description: [
                    <span className="yourClass">{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.`
                ],
            },

            {
                titleName: "JS String Methods",
                iconName: faDotCircle,
                description: [
                    <span className="yourClass">{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.1`
                ],
            },

            {
                title: [<span className={jsStyle.title}>Objects</span>],
            },

            {
                titleName: "JS Events",
                iconName: faDotCircle,
                description: [
                    <span className="yourClass">{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.1`
                ],
            },

            {
                titleName: "JS Strings",
                iconName: faDotCircle,
                description: [
                    <span className="yourClass">{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.`
                ],
            },

            {
                titleName: "JS String Methods",
                iconName: faDotCircle,
                description: [
                    <span className="yourClass">{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.1`
                ],
            },

            {
                titleName: "JS Strings",
                iconName: faDotCircle,
                description: [
                    <span className="yourClass">{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.`
                ],
            },

            {
                titleName: "JS String Methods",
                iconName: faDotCircle,
                description: [
                    <span className="yourClass">{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.1`
                ],
            },

            {
                title: [<span className={jsStyle.title}>ECMAScript 6</span>],
            },

            {
                titleName: "JS Events",
                iconName: faDotCircle,
                description: [
                    <span className="yourClass">{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.1`
                ],
            },

            {
                titleName: "JS Strings",
                iconName: faDotCircle,
                description: [
                    <span className="yourClass">{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.`
                ],
            },

            {
                titleName: "JS String Methods",
                iconName: faDotCircle,
                description: [
                    <span className="yourClass">{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.1`
                ],
            },

            {
                titleName: "JS Strings",
                iconName: faDotCircle,
                description: [
                    <span className="yourClass">{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.`
                ],
            },

            {
                titleName: "JS String Methods",
                iconName: faDotCircle,
                description: [
                    <span className="yourClass">{one}</span>,
                    ` advanced diverted domestic sex repeated bringing you old.1`
                ],
            },

        ]
    );
}

export default JavaScriptLessonObject;